export const selectfibre = [
    {value: '', label: 'Any'},
    {value: 'yes', label: 'Yes'},
    {value: 'no', label: 'No'}
  ]

export const selectpet_friendly = [
    {value: '', label: 'Any'},
    {value: 'yes', label: 'Yes'},
    {value: 'no', label: 'No'}
  ]

  export const selectproperty_type = [
    {value: '', label: 'Any'},
    {value: 'Apartment', label: 'Apartment'},
    {value: 'House', label: 'House'},
    {value: 'Townhouse', label: 'Townhouse'},
    {value: 'Unit', label: 'Unit'},
  ]

  
  export const selectbathrooms = [
    {value: '', label: 'Any'},
    {value: '1', label: '1'},
    {value: '2', label: '2'},
    {value: '3', label: '3'},
    {value: '4', label: '4'},
    {value: '5', label: '5'},
    {value: '6+', label: '6+'},
  ]

  
  export const selectbedrooms = [
    {value: '', label: 'Any'},
    {value: '1', label: '1'},
    {value: '2', label: '2'},
    {value: '3', label: '3'},
    {value: '4', label: '4'},
    {value: '5', label: '5'},
    {value: '6+', label: '6+'},
  ]

  export const selectprice_to = [
    {value: '', label: 'Any'},
    {value: '100', label: '$100'},
    {value: '200', label: '$200'},
    {value: '300', label: '$300'},
    {value: '400', label: '$400'},
    {value: '500', label: '$500'},
    {value: '600', label: '$600'},
    {value: '700', label: '$700'},
    {value: '800', label: '$800'},
    {value: '900', label: '$900'},
    {value: '1000', label: '$1000+'},
  ]

  export const selectprice_from = [
    {value: '', label: 'Any'},
    {value: '100', label: '$100'},
    {value: '200', label: '$200'},
    {value: '300', label: '$300'},
    {value: '400', label: '$400'},
    {value: '500', label: '$500'},
    {value: '600', label: '$600'},
    {value: '700', label: '$700'},
    {value: '800', label: '$800'},
    {value: '900', label: '$900'},
    {value: '1000', label: '$1000+'},
  ]

 export const selectsuburbs = [
    {value: '', label: 'Any'},
    {value: 'Albany', label: 'Albany'},
    {value: 'Ararimu', label: ' Ararimu'},
    {value: 'Army Bay', label: ' Army Bay'},
    {value: 'Bayview', label: ' Bayview'},
    {value: 'Beachlands', label: ' Beachlands'},
    {value: 'Birkenhead', label: ' Birkenhead'},
    {value: 'Blockhouse Bay', label: ' Blockhouse Bay'},
    {value: 'Bucklands Beach', label: ' Bucklands Beach'},
    {value: 'City Centre', label: ' City Centre'},
    {value: 'Dannemora', label: ' Dannemora'},
    {value: 'Devonport', label: ' Devonport'},
    {value: 'Eden Terrace', label: ' Eden Terrace'},
    {value: 'Epsom', label: ' Epsom'},
    {value: 'Forrest Hill', label: ' Forrest Hill'},
    {value: 'Freemans Bay', label: ' Freemans Bay'},
    {value: 'Glen Eden', label: ' Glen Eden'},
    {value: 'Glen Innes', label: ' Glen Innes'},
    {value: 'Glenfield', label: ' Glenfield'},
    {value: 'Goodwood Heights', label: ' Goodwood Heights'},
    {value:  'Greenlane', label: ' Greenlane'},
    {value: 'Grey Lynn', label: ' Grey Lynn'},
    {value: 'Gulf Harbour', label: ' Gulf Harbour'},
    {value: 'Half Moon Bay', label: ' Half Moon Bay'},
    {value: 'Hauraki', label: ' Hauraki'},
    {value: 'Herne Bay', label: ' Herne Bay'},
    {value: 'Hillsborough', label: ' Hillsborough'},
    {value: 'Hobsonville', label: ' Hobsonville'},
    {value: 'Howick', label: ' Howick'},
    {value: 'Huapai', label: ' Huapai'},
    {value: 'Kensington', label: ' Kensington'},
    {value: 'Kumeu', label: ' Kumeu'},
    {value: 'Lynfield', label: ' Lynfield'},
    {value: 'Mangere East', label: ' Mangere East'},
    {value: 'Manukau', label: ' Manukau'},
    {value: 'Manurewa', label: ' Manurewa'},
    {value: 'Manurewa East', label: ' Manurewa East'},
    {value: 'Massey', label: ' Massey'},
    {value: 'Meadowbank', label: ' Meadowbank'},
    {value: 'Milford', label: ' Milford'},
    {value: 'Millwater', label: ' Millwater'},
    {value: 'Mt Albert', label: ' Mt Albert'},
    {value: 'Mt Eden', label: ' Mt Eden'},
    {value: 'Mt Roskill', label: ' Mt Roskill'},
    {value: 'Mt Wellington', label: ' Mt Wellington'},
    {value: 'Murrays Bay', label: ' Murrays Bay'},
    {value: 'New Lynn', label: ' New Lynn'},
    {value: 'New Windsor', label: ' New Windsor'},
    {value: 'Newmarket', label: ' Newmarket'},
    {value: 'Northcote', label: ' Northcote'},
    {value: 'Northcross', label: ' Northcross'},
    {value: 'Northpark', label: ' Northpark'},
    {value: 'Onehunga', label: ' Onehunga'},
    {value: 'Orewa', label: ' Orewa'},
    {value: 'Otahuhu', label: ' Otahuhu'},
    {value: 'Pakuranga', label: ' Pakuranga'},
    {value: 'Panmure', label: ' Panmure'},
    {value: 'Papakura', label: ' Papakura'},
    {value: 'Papatoetoe', label: ' Papatoetoe'},
    {value: 'Parnell', label: ' Parnell'},
    {value: 'Pt Chevalier', label: ' Pt Chevalier'},
    {value: 'Puhoi', label: ' Puhoi'},
    {value: 'Pukekohe', label: ' Pukekohe'},
    {value: 'Red Beach', label: ' Red Beach'},
    {value: 'Remuera', label: ' Remuera'},
    {value: 'Royal Oak', label: ' Royal Oak'},
    {value: 'Ruakaka', label: ' Ruakaka'},
    {value: 'Silverdale', label: ' Silverdale'},
    {value: 'St Heliers', label: ' St Heliers'},
    {value: 'St Johns', label: ' St Johns'},
    {value: 'Stanmore Bay', label: ' Stanmore Bay'},
    {value: 'Stonefields', label: ' Stonefields'},
    {value: 'Sunnyvale', label: ' Sunnyvale'},
    {value: 'Takanini', label: ' Takanini'},
    {value: 'Takapuna', label: ' Takapuna'},
    {value: 'Te Atatu South', label: ' Te Atatu South'},
    {value: 'Three Kings', label: ' Three Kings'},
    {value: 'Tikipunga', label: ' Tikipunga'},
    {value: 'Titirangi', label: ' Titirangi'},
    {value: 'Torbay', label: ' Torbay'},
    {value: 'Waimauku', label: ' Waimauku'},
    {value: 'Waiuku', label: ' Waiuku'},
    {value: 'Welcome Bay', label: ' Welcome Bay'},
    {value: 'Beachlands', label: 'Beachlands'},
    {value: 'Blockhouse Bay', label: 'Blockhouse Bay'},
    {value: 'Browns Bay', label: 'Browns Bay'},
    {value: 'City Centre', label: 'City Centre'},
    {value: 'Dairy Flat', label: 'Dairy Flat'},
    {value: 'Devonport', label: 'Devonport'},
    {value: 'East Tamaki', label: 'East Tamaki'},
    {value: 'Eastern Beach', label: 'Eastern Beach'},
    {value: 'Epsom', label: 'Epsom'},
    {value: 'Flat Bush', label: 'Flat Bush'},
    {value: 'Forrest Hill', label: 'Forrest Hill'},
    {value: 'Freemans Bay', label: 'Freemans Bay'},
    {value: 'Glen Eden', label: 'Glen Eden'},
    {value: 'Glenfield', label: 'Glenfield'},
    {value: 'Grafton', label: 'Grafton'},
    {value: 'Henderson', label: 'Henderson'},
    {value: 'Hillcrest', label: 'Hillcrest'},
    {value: 'Hillsborough', label: 'Hillsborough'},
    {value: 'Hobsonville', label: 'Hobsonville'},
    {value: 'Kelston', label: 'Kelston'},
    {value: 'Long Bay', label: 'Long Bay'},
    {value: 'Manurewa', label: 'Manurewa'},
    {value: 'Massey', label: 'Massey'},
    {value: 'Maungatapu', label: 'Maungatapu'},
    {value: 'Meadowbank', label: 'Meadowbank'},
    {value: 'Mission Bay', label: 'Mission Bay'},
    {value: 'Mt Albert', label: 'Mt Albert'},
    {value: 'Mt Eden', label: 'Mt Eden'},
    {value: 'Mt Roskill', label: 'Mt Roskill'},
    {value: 'Newmarket', label: 'Newmarket'},
    {value: 'Ngunguru', label: 'Ngunguru'},
    {value: 'One Tree Hill', label: 'One Tree Hill'},
    {value: 'Orewa', label: 'Orewa'},
    {value: 'Otahuhu', label: 'Otahuhu'},
    {value: 'Pakuranga', label: 'Pakuranga'},
    {value: 'Papatoetoe', label: 'Papatoetoe'},
    {value: 'Parnell', label: 'Parnell'},
    {value: 'Pt Chevalier', label: 'Pt Chevalier'},
    {value: 'Pukekohe', label: 'Pukekohe'},
    {value: 'Ranui', label: 'Ranui'},
    {value: 'Remuera', label: 'Remuera'},
    {value: 'Schnapper Rock', label: 'Schnapper Rock'},
    {value: 'Silverdale', label: 'Silverdale'},
    {value: 'St Heliers', label: 'St Heliers'},
    {value: 'St Johns', label: 'St Johns'},
    {value: 'Stanmore Bay', label: 'Stanmore Bay'},
    {value: 'Stonefields', label: 'Stonefields'},
    {value: 'Sunnyook', label: 'Sunnyook'},
    {value: 'Takapuna', label: 'Takapuna'},
    {value: 'Te Atatu South', label: 'Te Atatu South'},
    {value: 'Three Kings', label: 'Three Kings'},
    {value: 'Totara Vale', label: 'Totara Vale'},
    {value: 'Unsworth Heights', label: 'Unsworth Heights'},
    {value: 'Waiuku', label: 'Waiuku'},
    {value: 'Warkworth', label: 'Warkworth'},
    {value: 'Waterview', label: 'Waterview'},
    {value: 'Woodhill', label: 'Woodhill'},
    {value: 'Wynyard Quarter', label: 'Wynyard Quarter'}] 

export const selectdistricts = [
    {value: '', label: 'Any'},
    { value: 'Auckland City', label: 'Auckland City' },
    { value: 'North Shore City', label: 'North Shore City' },
    { value: 'Manukau City', label: 'Manukau City' },
    { value: 'Rodney District', label: 'Rodney District' },
    { value: 'Waitakere City', label: 'Waitakere City' }
  ]